import type {
  AlertaColegio,
  Edificio,
  MovimientoResidente,
  Officer,
  Residente,
  Visita,
} from "./types"

export const officersSeed: Officer[] = [
  {
    id: "OF-COL-01",
    nombre: "Oficial Juárez",
    turno: "Nocturno",
    avatar: "https://i.pravatar.cc/120?img=12",
    gate: "Caseta Principal",
  },
  {
    id: "OF-COL-02",
    nombre: "Officer Ramos",
    turno: "Nocturno",
    avatar: "https://i.pravatar.cc/120?img=33",
    gate: "Gate 3 - North",
  },
]

export const edificiosSeed: Edificio[] = [
  { id: "ed-cain", nombre: "Edificio Cain-Murray", ocupacion: 210, capacidad: 250 },
  { id: "ed-ray", nombre: "Edificio Ray Lindley", ocupacion: 185, capacidad: 200 },
  { id: "ed-bernal", nombre: "Residencias Ignacio Bernal", ocupacion: 340, capacidad: 400 },
  { id: "ed-gaos", nombre: "Edificio Jose Gaos", ocupacion: 121, capacidad: 150 },
]

export const residentesSeed: Residente[] = [
  {
    id: "158293",
    nombre: "Alejandro Ramírez",
    carrera: "Ingeniería en Sistemas",
    semestre: 6,
    edificio: "Cain Murray",
    habitacion: "Villa I - Hab 204B",
    avatar: "https://i.pravatar.cc/120?img=51",
    estado: "en_campus",
  },
  {
    id: "161044",
    nombre: "María José Flores",
    carrera: "Diseño de Información",
    semestre: 4,
    edificio: "Ignacio Bernal",
    habitacion: "Torre A - Hab 512",
    avatar: "https://i.pravatar.cc/120?img=47",
    estado: "fuera",
  },
  {
    id: "159382",
    nombre: "David G. Smith",
    carrera: "Administración de Negocios",
    semestre: 8,
    edificio: "Ray Lindley",
    habitacion: "Villa II - Hab 101C",
    avatar: "https://i.pravatar.cc/120?img=15",
    estado: "en_campus",
  },
  {
    id: "162271",
    nombre: "Sarah Williams",
    carrera: "Derecho",
    semestre: 5,
    edificio: "Cain Murray",
    habitacion: "Villa I - Hab 303A",
    avatar: "https://i.pravatar.cc/120?img=44",
    estado: "invitado",
  },
  {
    id: "165432",
    nombre: "Mariana Sosa",
    carrera: "Arquitectura",
    semestre: 7,
    edificio: "Cain Murray",
    habitacion: "Villa I - Hab 410D",
    avatar: "https://i.pravatar.cc/120?img=20",
    estado: "en_campus",
  },
  {
    id: "167890",
    nombre: "Roberto Méndez",
    carrera: "Ingeniería Industrial",
    semestre: 9,
    edificio: "Ignacio Bernal",
    habitacion: "Torre B - Hab 207",
    avatar: "https://i.pravatar.cc/120?img=11",
    estado: "en_campus",
  },
  {
    id: "164221",
    nombre: "Luisa Ortega",
    carrera: "Psicología",
    semestre: 3,
    edificio: "Jose Gaos",
    habitacion: "Edif. C - Hab 105",
    avatar: "https://i.pravatar.cc/120?img=29",
    estado: "fuera",
  },
  {
    id: "166543",
    nombre: "Juan Pablo García",
    carrera: "Computer Science",
    semestre: 7,
    edificio: "Cain Murray",
    habitacion: "Villa I - Hab 502",
    avatar: "https://i.pravatar.cc/120?img=8",
    estado: "en_campus",
  },
  {
    id: "168901",
    nombre: "Andrea Castillo",
    carrera: "Comunicación",
    semestre: 4,
    edificio: "Ray Lindley",
    habitacion: "Villa II - Hab 203A",
    avatar: "https://i.pravatar.cc/120?img=23",
    estado: "fuera",
  },
  {
    id: "170112",
    nombre: "Carlos Mendoza",
    carrera: "Mecatrónica",
    semestre: 5,
    edificio: "Jose Gaos",
    habitacion: "Edif. C - Hab 312",
    avatar: "https://i.pravatar.cc/120?img=14",
    estado: "en_campus",
  },
  {
    id: "171223",
    nombre: "Valeria Núñez",
    carrera: "Negocios Internacionales",
    semestre: 6,
    edificio: "Ignacio Bernal",
    habitacion: "Torre A - Hab 408",
    avatar: "https://i.pravatar.cc/120?img=32",
    estado: "invitado",
  },
  {
    id: "172334",
    nombre: "Fernando Rivas",
    carrera: "Finanzas",
    semestre: 8,
    edificio: "Cain Murray",
    habitacion: "Villa I - Hab 109B",
    avatar: "https://i.pravatar.cc/120?img=58",
    estado: "en_campus",
  },
]

export const movimientosSeed: MovimientoResidente[] = [
  {
    id: "mov-1",
    residenteId: "165432",
    edificioId: "ed-cain",
    hora: "23:45",
    tipo: "entrada",
    estado: "normal",
  },
  {
    id: "mov-2",
    residenteId: "167890",
    edificioId: "ed-bernal",
    hora: "23:12",
    tipo: "entrada",
    estado: "ebriedad",
  },
  {
    id: "mov-3",
    residenteId: "164221",
    edificioId: "ed-gaos",
    hora: "22:55",
    tipo: "salida",
    estado: "autorizada",
  },
  {
    id: "mov-4",
    residenteId: "158293",
    edificioId: "ed-cain",
    hora: "22:38",
    tipo: "entrada",
    estado: "normal",
  },
  {
    id: "mov-5",
    residenteId: "166543",
    edificioId: "ed-cain",
    hora: "22:15",
    tipo: "salida",
    estado: "autorizada",
  },
]

export const alertasSeed: AlertaColegio[] = [
  {
    id: "al-1",
    edificioId: "ed-bernal",
    residenteId: "167890",
    tipo: "ebriedad",
    severidad: "alta",
    descripcion: "Caso de ebriedad detectado en caseta nocturna",
    timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    estado: "activa",
  },
  {
    id: "al-2",
    edificioId: "ed-cain",
    tipo: "items_prohibidos",
    severidad: "media",
    descripcion: "Visitante con vape detectado en Villa I",
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    estado: "activa",
  },
  {
    id: "al-3",
    edificioId: "ed-ray",
    tipo: "ronda",
    severidad: "info",
    descripcion: "Ronda nocturna completada en Ray Lindley",
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    estado: "atendida",
  },
  {
    id: "al-4",
    edificioId: "ed-gaos",
    tipo: "incidente",
    severidad: "media",
    descripcion: "Reporte de ruido excesivo en Edif. C",
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    estado: "activa",
  },
]

export const visitasSeed: Visita[] = [
  {
    id: "vis-1",
    nombreCompleto: "Ricardo Morales Sánchez",
    categoria: "comunidad_udlap",
    tipoAcceso: "peatonal",
    edificioDestinoId: "ed-gaos",
    fechaHora: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    multipleEntrada: false,
    tipoId: "INE / Credencial Oficial",
    estatusVisitante: "sin_antecedentes",
    ubicacionEntrada: "Puerta Principal Sur",
  },
  {
    id: "vis-2",
    nombreCompleto: "Juan Pablo García",
    categoria: "comunidad_udlap",
    tipoAcceso: "peatonal",
    edificioDestinoId: "ed-cain",
    fechaHora: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    multipleEntrada: false,
    tipoId: "Credencial UDLAP",
    estatusVisitante: "sin_antecedentes",
    ubicacionEntrada: "Caseta Cain Murray",
  },
]
